version: '3.3'

services:
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "5432:5432"
    volumes:
      - db:/data
    environment:
      - POSTGRES_PASSWORD=test1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
volumes:
  db:
    driver: local