CREATE TABLE faq_assistant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT(timezone('utc', now())),
    deleted_at TIMESTAMP NULL,
    CONSTRAINT pk_faq_assistant PRIMARY KEY (id)
);

CREATE TABLE embedding (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    assistant_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP DEFAULT(timezone('utc', now())),
    deleted_at TIMESTAMP NULL,
    CONSTRAINT pk_embedding PRIMARY KEY (id)
);